baseURL = "https://coronavirus.netlify.com"
languageCode = "pt-br"
title = "COVID-19 Brasil"
theme = "minimal"

[params]
    author = "Maurício Vancine"
    description = "Análises espaciais simples da distribuição do COVID-19"
    githubUsername = "#mauriciovancine"
    accent = "#528b8b"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["R"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/r-covid-brasil/"
    name = "Brasil"
    weight = 2
    
[[menu.main]]
    url = "/about/"
    name = "Sobre"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:mauricio.vancine@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/mauriciovancine/coronavirus"
    name = "github"
    weight = 2
